#!/bin/sh

module="fiodriver"
device="fio"
mode="664"

/sbin/insmod ./$module.ko $* || exit 1

rm -f /dev/${device}

major=$(awk '$2=='\"$module\"' {print $1}' /proc/devices)

mknod /dev/${device} c $major 0

group="tgauger"

chgrp $group /dev/${device}
chmod $mode  /dev/${device}
