SOURCES := AuxSampleApplication.c

LIBRARIES := -lpthread

INCLUDES := ../FrontPanelDriver/front_panel.h

OBJECTS := $(SOURCES:.c=.o)

.c.o:
	cc -g -O -Wall -I../ -I../FrontPanelDriver -c $<

## Targets
TARGET := AuxSampleApplication

all: $(TARGET)

$(TARGET) : $(OBJECTS) $(INCLUDES)
	cc -g -O -o $@ $(OBJECTS) $(LIBRARIES)

install:
	cp $(TARGET) $(HOME)/bin
	chmod 755 $(HOME)/bin/$(TARGET)

clean:
	rm -f $(OBJECTS) $(TARGET) $(HOME)/bin/$(TARGET)
